### ISSUE TITLE
How much CUDA memory is needed?

### ISSUE THREAD

**Issue by Ardor-Wu** [microsoft/robustdg#19]

**Comment by Ardor-Wu** [comment]
I encountered such error:
RuntimeError: CUDA out of memory. Tried to allocate 980.00 MiB (GPU 0; 15.78 GiB total capacity; 13.73 GiB already allocated; 393.75 MiB free; 14.09 GiB reserved in total by PyTorch)

On two Tesla V100 SXM2 16 GB.  What should I do to run the command in "robustdg_getting_started.ipynb"? I changed the batch size to 128 and it worked, but the performance significantly dropped. I really appreciate any help you can provide.

**Comment by divyat09** [comment]
For MatchDG Phase-1 (Contrastive Learning Phase), batch size 256 requires around 32 GB GPU memory. 

Updated Issue: https://github.com/microsoft/robustdg/issues/20
